name: Build and Deploy
on:
  push:
    branches:
      - develop
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Edit package.json 📄
        run: npx json -I -f package.json -e 'this.homepage="https://app.dev.sarcophagus.io"'

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build

      - name: Install SSH Client 🔑
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY_DEV }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          SSH: true
          REPOSITORY_NAME: sarcophagus-org/sarcophagus-app_dev
          BRANCH: gh-pages
          FOLDER: build
          CLEAN: true
